config/routes.rb
Rails.application.routes.draw do

   ### ACCESS + MAIN ROUTES
  root 'access#login'

  get '/', to: 'access#login'

  get 'index', to: 'access#login'

  post 'signup', to: 'access#create', as: 'create_user'

  get 'signup', to: 'access#new'

  get 'home', to: 'users#index'

  get 'login', to: 'access#login', as: 'login'

  get 'logout', to: 'access#logout'

  post 'login', to: 'access#attempt_login'

  ### USERS ROUTES
  get 'users', to: 'users#index', as: 'users'

  get 'users/:id/edit', to: 'users#edit', as: 'users_edit'

  get 'users/:id', to: 'users#show', as: 'users_show'

  delete 'users/:id', to: 'users#destroy'

  patch 'users/:id/edit', to: 'users#update'

  ### VIDEOS ROUTES
  get 'videos', to: 'videos#index', as: 'videos'

  ### MARKERS ROUTES

  get 'markers', to: 'markers#index', as: 'markers'

  post 'markers', to: 'markers#create'

end

app/models/marker.rb
class Marker < ActiveRecord::Base
  belongs_to :user
  validates :tag,
    presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :markers
  validates :username,
    uniqueness: true,
    presence: true
  validates :password,
    length: {minimum: 5}
end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  before_action :confirm_logged_in, except: [:new, :create, :attempt_login, :login, :logout]
  before_action :prevent_login_signup, only: [:login, :new]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if(@user.save)
      session[:user_id] = @user.id
      flash[:success] = "You are now logged in!"
      redirect_to users_path
    else
      render :new
    end

  end

  def login
  end

  def attempt_login

    if params[:username].present? && params[:password].present?
      found_user = User.where(username: params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if !found_user
      flash.now[:alert] = "Invalid username"
      render :login
    elsif !authorized_user
      flash.now[:alert] = "Invalid password"
      render :login
    else
      session[:user_id] = authorized_user.id
      flash[:success] = "You are now logged in."
      redirect_to users_path
    end

  end

  def logout
    # mark user as logged out
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to login_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

private

  # Ensure a user is logged in
  def confirm_logged_in
    unless session[:user_id]
      flash[:notice] = "Please log in."
      redirect_to('/login')
    end
  end

  # Stop a logged in user from going to the sign up page
  def prevent_login_signup
    if session[:user_id]
      redirect_to('/home')
    end
  end

  # Prevent a user from going to another users page
  def prevent_user(user)
    if user.nil? or session[:user_id] != user.id
      redirect_to('/videos')
    end
  end

  # Assign a current_user
  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
respond_to :json

def create

  marker_params = params.permit!

  marker = Marker.new #create(params.permit!)

  marker.user_id = 1 #session[:user_id]
  marker.tag = marker_params[:tag]
  marker.video_time = marker_params[:video_time]
  marker.video_id = marker_params[:video_id]
  marker.video_length = marker_params[:video_length]
  marker.comment = marker_params[:comment]

  marker.save
  # binding.pry
  render json: marker

end

def index
  markers = Marker.all
  render json: markers
end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
      redirect_to('/videos')
  end


  def show
    @user = User.find_by_id(params[:id])
    prevent_user(@user)
  end

  def edit
    @user = User.find_by_id(params[:id])
    prevent_user(@user)
  end

   def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)

    if(@user.save)
      session[:user_id] = @user.id
      flash[:success] = "You're profile is updated"
      redirect_to '/home'
    else
      render :edit
    end

   end

  def destroy
    user = User.find_by_id(params[:id])
    user.destroy
    redirect_to '/index'
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :current_user
  before_action :confirm_logged_in

  def index
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/access/login.html.erb
<div class="container text-center">
  <%= form_tag(login_path) do %>
<br>
<div class="form-group">
      <%= label_tag(:username, nil,class: "control-label") %>
      <%= text_field_tag :username, params[:username], autofocus: true, class: "form-control" %>

</div>
<div class="form-group">

      <%= label_tag(:password,nil, class: "control-label") %>
      <%= password_field_tag(:password, nil, class: "form-control") %>
</div>

<div class="form-group">

      &nbsp;
      <%= submit_tag("Log In", class: "btn btn-primary") %>
</div>

  <% end %>
  <p><%= link_to("Don't have an account? Sign up for one here", controller: 'access', action: 'new') %></p>
</div>

app/views/access/new.html.erb
<div class="container text-center">

<% if @user.errors.any? %>
  <ul class = "text-danger list-unstyled">
   <%  for err in @user.errors.full_messages %>
    <li>
      <%= err%>
    </li>
    <% end %>
  </ul>
<% end %>

  <%= form_for(@user, url: create_user_path) do |f|%>
<br>
<div class="form-group">
      <%= f.label(:username, class: "control-label") %>
      <%= f.text_field :username, autofocus: true, class: "form-control" %>

</div>
<div class="form-group">

      <%= f.label(:password, class: "control-label") %>
      <%= f.password_field(:password, class: "form-control") %>
</div>
<div class="form-group">

      <%= f.label(:password_confirmation, class: "control-label") %>
      <%= f.password_field(:password_confirmation, class: "form-control") %>
</div>
<div class="form-group">

      <%= f.submit("Sign Up", class: "btn btn-primary") %>
</div>

  <% end %>


<p><%= link_to("Have an account already? Sign up here", 'login') %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoMarker</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <script src="https://www.youtube.com/iframe_api"></script>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

       <!-- Optional theme -->
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

</head>
<body class = "container">

  <% if flash[:notice].present? %>
    <div class="container text-center alert alert-warning">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <% if flash[:alert].present? %>
    <div class="container text-center alert alert-danger">
      <%= flash[:alert] %>
    </div>
  <% end %>

    <% if flash[:success].present? %>
    <div class="container text-center alert alert-success">
      <%= flash[:success] %>
    </div>
  <% end %>

<%= yield %>
</body>
</html>

app/views/users/edit.html.erb
<div class="container text-center">

<% if @user.errors.any? %>
  <ul class = "text-danger list-unstyled">
   <%  for err in @user.errors.full_messages %>
    <li>
      <%= err%>
    </li>
    <% end %>
  </ul>
<% end %>

  <%= form_for(@user, url: users_edit_path) do |f|%>
<br>
<div class="form-group">
      <%= f.label(:username, class: "control-label") %>
      <%= f.text_field :username, autofocus: true, class: "form-control" %>

</div>
<div class="form-group">

      <%= f.label(:password, class: "control-label") %>
      <%= f.password_field(:password, class: "form-control") %>
</div>
<div class="form-group">

      <%= f.label(:password_confirmation, class: "control-label") %>
      <%= f.password_field(:password_confirmation, class: "form-control") %>
</div>
<div class="form-group">

      <%= f.submit("Sign Up", class: "btn btn-info") %>
</div>

  <% end %>

</div>

app/views/users/index.html.erb
<h1>Admin Page</h1>

<% @users.each do |user| %>
<p>
  ID <%= user.id%>
  <br>
  Username: <%= user.username %>
  <br>
  is_admin? <%= user.is_admin %>
  <br>
</p>
<% end %>

<p>
  <a href = "/logout" class = "btn btn-danger">Logout</a>
</p>

app/views/users/show.html.erb
<h1>Your profile</h1>

<p>
  ID: <%= @user.id %>
</p>

<p>
  Username: <%= @user.username %>
</p>

<%= link_to("Edit your profile", users_edit_path) %>

app/views/videos/index.html.erb
<h1>videos page</h1>



<!-- 1. The <iframe> (and video player) will replace this <div> tag. -->
<div id="player"></div>
<div id="timeline">
<img src="/assets/line.svg" alt="">
</div>

<input type="submit" value="Interesting" id="time" name="interesting" class="btn btn-info btn-xs">

<input type="submit" value="Rephrase" id="time" name="rephrase" class="btn btn-success btn-xs">

<input type="submit" value="Stop" id="time" name="stop" class="btn btn-warning btn-xs">

<input type="submit" value="Drill" id="time" name="drill" class="btn btn-danger btn-xs">
&nbsp
<input type="text" name="" id="comment" placeholder="Write a comment" autofocus>